### ISSUE TITLE
how to build ughh database?

### ISSUE THREAD

**Issue by BaylorLyu** [czbiohub-sf/MIDAS2#102]
use command midas2 database can not download uhgg database on local. Can you write a workflow show how to build uhgg database？

**Comment by zhaoc1** [comment]
Hi,

Please refer to https://midas2.readthedocs.io/en/latest/download_midasdb.html for downloading MIDASDB.

We don't build UHGG ourselves, and imported from the UHGG catalog: https://www.nature.com/articles/s41587-020-0603-3

If you are interested in building custom MIDASDB, please refer to this page: https://midas2.readthedocs.io/en/latest/advanced_topics.html#build-your-own-midasdb

Chunyu
