### ISSUE TITLE
How to keep the alignment?

### ISSUE THREAD

**Issue by FranckLejzerowicz** [czbiohub-sf/MIDAS2#120]
Hello,

In [this](https://midas2.readthedocs.io/en/latest/output.html#single-sample-results-layout) ReadTheDocs page, it is shown in the anatomy of the per-sample `run_snps` outputs, that the alignments are present:
```
|- temp
     |- snps
        |- repgenomes.bam              run_snps        Rep-genome alignment file
        |- {species}/snps_XX.tsv.lz4
  |- bt2_indexes
     |- snps/repgenomes.*              run_snps        Sample-specific rep-genome database
```

However, both the `temp` and `bt_indexes` folder turn out empty after a successful run of `run_snps`. 

I do not remove these files and I do see in the stdout:

- lines such as:
```
1695133677.6:  'samtools index -@ 4 /<my_path>/temp/snps/111210/111210.sorted.bam'
```
but this file is nowhere to be found after completion.

I consider hacking the tool for not-removing these files that would be useful to my work.

Please, is there a way/flag to tell midas2 to keep these output files?

Thanks,
Franck

**Comment by FranckLejzerowicz** [comment]
Probably answering to myself here, but the code seems to allow for `--debug` to get me where I want - correct?
https://github.com/czbiohub-sf/MIDAS2/blob/a293ce62355e88dc0f12145871ff47110bc8f712/midas2/subcommands/run_snps.py#L850-L853
Thanks

**Comment by zhaoc1** [comment]
Yes! `--debug` is the way to go for keeping all the temp files, including the alignment files.
