### ISSUE TITLE
midas2 v1.0.9

### ISSUE THREAD

**Issue by qinghong2019** [czbiohub-sf/MIDAS2#122]
after download the v1.0.9 source code, and get into the directory
conda env create -n midas2 -f midas2.yml
return error message: 
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - midas2=1.0.9

**Comment by zhaoc1** [comment]
Hi,

I updated the midas2.yml, so please re-download the source code and re-install. 

However, I recommend you refer to #121 , and install MIDAS2 via conda install:

```
conda config --set channel_priority flexible
conda install -c zhaoc1 -c conda-forge -c bioconda-c anaconda -c defaults midas2
```

Thanks!
Chunyu

**Comment by qinghong2019** [comment]
Hi, Chunyu
I redownloaded, the same error message:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - midas2=1.1.0.

I tried:

conda config --set channel_priority flexible
conda install -c zhaoc1 -c conda-forge -c bioconda-c anaconda -c defaults midas2

it returns:

usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: midas2

Thank you!

Qinghong

**Comment by zhaoc1** [comment]
Okay. I will put this issue on my TODO list. At the mean time, can you try the conda install approach?

**Comment by zhaoc1** [comment]
Apology for the confusion. I again updated the midas2.yml and just tested install from source on a linux server.

1. please install the v1.1.0 midas2, which is the current master branch of https://github.com/czbiohub/MIDAS2.git
2. Updated commands (just about the version):
```
git clone git clone https://github.com/czbiohub/MIDAS2.git
cd MIDAS2

conda env create -n midas2v1.1.0 -f midas2.yml
conda activate midas2v1.1.0 

pip install .
```

Thanks.
Chunyu

**Comment by qinghong2019** [comment]
it worked now. Thank you for the quick response and help

**Comment by zhaoc1** [comment]
You are welcome :)
