### ISSUE TITLE
midasv3 chunk size error with midas2 database init

### ISSUE THREAD

**Issue by uel3** [czbiohub-sf/MIDAS2#136]
I am having trouble with the  $midas2 database --init --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg with the latest midasv3 update. 

conda list midas2
packages in environment at ~/.conda/envs/midasv3:

Name                    Version                   Build  Channel
midas2                    2.0.0.rc3                  py_0    zhaoc1

However older midas2 conda environments work 

 conda list midas2
 packages in environment at ~/.conda/envs/midas2.0:

 Name                    Version                   Build  Channel
midas2                    1.0.2                    pypi_0    pypi

Here is how I installed midasv3
mamba create -n midasv3 -c zhaoc1 -c conda-forge -c bioconda -c anaconda -c defaults midas2

conda activate midasv3
Running in ~/MIDAS2/tests
initiating midas2 db
midas2 database --init --midasdb_name uhgg --midasdb_dir my_midasdb_uhgg

Output

1714143353.0:  Initate MIDASDB uhgg to my_midasdb_uhgg::start
1714144132.0:  Initate MIDASDB uhgg to my_midasdb_uhgg::finish
1714144132.0:  Download chunks for MIDASDB uhgg to my_midasdb_uhgg::start
Traceback (most recent call last):
  File "/.conda/envs/midasv3/bin/midas2", line 10, in <module>
    sys.exit(main())
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/__main__.py", line 25, in main
    return subcommand_main(subcommand_args)
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/subcommands/database.py", line 146, in main
    init_midasdb(args)
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/subcommands/database.py", line 29, in init_midasdb
    midasdb.fetch_files("chunks")
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/models/midasdb.py", line 190, in fetch_files
    return self.fetch_tarball(filename, list_of_species)
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/models/midasdb.py", line 252, in fetch_tarball
    md5_fetched = file_md5sum(_fetched_file)
  File "/.conda/envs/midasv3/lib/python3.9/site-packages/midas2/models/midasdb.py", line 364, in file_md5sum
    return md5(open(local_file, "rb").read()).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: '~/MIDAS2/tests/my_midasdb_uhgg/chunks/sites/run/chunksize.50000/100001/GUT_GENOME000001.json'

Any help would be appreciated with this matter. Thank you.

**Comment by zhaoc1** [comment]
Hi, 

MIDAS2 is currently under updates to version 3, with significant changes to the pangenome structure. I haven't finished the publishing of the new MIDASDB yet. Please use the Release version (https://github.com/czbiohub-sf/MIDAS2/releases/tag/v1.0.9) for now. Thanks for the understanding. Hopefully I can publish the new db within the next month.

Thank you
Chunyu

**Comment by uel3** [comment]
Thank you for getting back to me. I will use release 1.0.9 in the meantime. Looking forward to the update. 

Candace
