### ISSUE TITLE
merge_snps error

### ISSUE THREAD

**Issue by luoqingqing777** [czbiohub-sf/MIDAS2#88]
Hello，i  downloaded one database for selected species of '145629' and finished run_snps step in following code
`midas2 run_snps --sample_name ${line}-1 reads/${line}.decon_1.fastq.gz -2 reads/${line}.decon_2.fastq.gz --midasdb_name gtdb --midasdb_dir my_midasdb_Catellicoccus  --species_list 145629 --select_threshold=-1 --num_cores 10 --advanced --ignore_ambiguous  midas2_output`
But there is somthing wrong with merge_snps:
`midas2 merge_snps --samples_list list_of_samples.tsv --midasdb_name gtdb --midasdb_dir my_midasdb_Catellicoccus  --genome_coverage 0.7 --num_cores 10 midas2_output/merge`

1654743241.2:  Across samples population SNV calling in subcommand merge_snps with args
1654743241.2:  {
1654743241.2:      "subcommand": "merge_snps",
1654743241.2:      "force": false,
1654743241.2:      "debug": false,
1654743241.2:      "zzz_worker_mode": false,
1654743241.2:      "batch_branch": "master",
1654743241.2:      "batch_memory": 378880,
1654743241.2:      "batch_vcpus": 48,
1654743241.2:      "batch_queue": "pairani",
1654743241.2:      "batch_ecr_image": "pairani:latest",
1654743241.2:      "midas_outdir": "midas2_output/merge",
1654743241.2:      "samples_list": "list_of_samples.tsv",
1654743241.2:      "midasdb_name": "gtdb",
1654743241.2:      "midasdb_dir": "my_midasdb_Catellicoccus",
1654743241.2:      "species_list": null,
1654743241.2:      "genome_depth": 5.0,
1654743241.2:      "genome_coverage": 0.7,
1654743241.2:      "sample_counts": 2,
1654743241.2:      "site_depth": 5,
1654743241.2:      "site_ratio": 3.0,
1654743241.2:      "site_prev": 0.9,
1654743241.2:      "snv_type": "common",
1654743241.2:      "snp_pooled_method": "prevalence",
1654743241.2:      "snp_maf": 0.05,
1654743241.2:      "snp_type": "bi, tri, quad",
1654743241.2:      "locus_type": "any",
1654743241.2:      "num_cores": 10,
1654743241.2:      "chunk_size": 1000000,
1654743241.2:      "advanced": false,
1654743241.2:      "robust_chunk": false
1654743241.2:  }
1654743241.6:  1 species pass the filter
1654743241.6:  Create OUTPUT directory.
1654743241.6:  'rm -rf midas2_output/merge/snps'
1654743241.6:  'mkdir -p midas2_output/merge/snps'
1654743241.6:  Create TEMP directory.
1654743241.6:  'rm -rf midas2_output/merge/temp/snps'
1654743241.6:  'mkdir -p midas2_output/merge/temp/snps'
1654743241.7:  MIDAS2::write_species_summary::start
1654743241.7:  MIDAS2::write_species_summary::finish
1654743242.7:  MIDAS2::design_chunks::start
1654743242.7:  ================= Total number of compute chunks: 2
1654743242.7:  MIDAS2::design_chunks::finish
1654743242.7:  MIDAS2::multiprocessing_map::start
1654743242.8:    MIDAS2::process::145629-0::start snps_worker
1654743242.8:      MIDAS2::chunk_worker::145629-0::start accumulate_samples
1654743242.8:    MIDAS2::process::145629-1::start snps_worker
1654743242.8:    MIDAS2::process::145629--1::wait collect_chunks
1654743242.8:      MIDAS2::chunk_worker::145629-1::start accumulate_samples
1654743242.8:  WARNING: Non-zero exit code 141 from reader of midas2_output/LRDYA/snps/145629.snps.tsv.lz4.
1654743243.1:  WARNING: Non-zero exit code 141 from reader of midas2_output/LRDYA/snps/145629.snps.tsv.lz4.
1654743243.1:    MIDAS2::process::145629--1::start collect_chunks
cat: midas2_output/merge/temp/snps/145629/cid.0_snps_info.tsv.lz4: No such file or directory
cat: midas2_output/merge/temp/snps/145629/cid.1_snps_info.tsv.lz4: No such file or directory
1654743243.1:  Bugs in the codes, keep the outputs for debugging purpose.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 270, in process
    snps_worker(species_id, chunk_id)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 293, in snps_worker
    chunk_worker(chunks_of_sites[chunk_id][0])
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 345, in chunk_worker
    accumulate(accumulator, proc_args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 378, in accumulate
    for row in select_from_tsv(stream, schema=curr_schema, selected_columns=snps_pileup_basic_schema, result_structure=dict):
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 392, in select_from_tsv
    assert False, f"Line {i + j} has {len(values)} columns;  was expecting {len(headers)}."
AssertionError: Line 0 has 13 columns;  was expecting 8.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/home/user02/miniconda3/envs/midas2.0/bin/midas2", line 8, in <module>
    sys.exit(main())
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/__main__.py", line 24, in main
    return subcommand_main(subcommand_args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 664, in main
    merge_snps(args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 653, in merge_snps
    raise error
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 643, in merge_snps
    proc_flags = multiprocessing_map(process, arguments_list, args.num_cores)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 532, in multiprocessing_map
    return _multi_map(func, items, num_procs, multiprocessing.Pool)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 520, in _multi_map
    return p.map(func, items, chunksize=1)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: Line 0 has 13 columns;  was expecting 8.

Thank you so much

**Comment by zhaoc1** [comment]
Hi, 

From your command line history `midas2_output/LRDYA/snps/145629.snps.tsv.lz4`, can you make sure the the sample name provided to the merge_snps command `--samples_list list_of_samples.tsv` is LRDYA?

Thanks,
Chunyu

**Comment by luoqingqing777** [comment]
Thank so much for your reply!
Yes, i am sure that  LRDYA sample name is included in `--samples_list list_of_samples.tsv`  

$ less ./list_of_samples.tsv 
sample_name     midas_outdir
ASQHA   midas2_output
DYBA    midas2_output
DYS2A   midas2_output
DYW1A   midas2_output
FAQHA   midas2_output
FAQHYA  midas2_output
HYBA    midas2_output
LRDYA   midas2_output
LRDYYA  midas2_output
LRHYA   midas2_output
LRHYYA  midas2_output
LRLSA   midas2_output
LRLSYA  midas2_output
LRQHA   midas2_output
LRQHWA  midas2_output
LRQHYWA midas2_output
LSBA    midas2_output
LSSA    midas2_output
LSWA    midas2_output
PCQHA   midas2_output
QHBA    midas2_output
QHPA    midas2_output
QHPDA   midas2_output
TFQHA   midas2_output

And although it did not finish the merge_snps step, there is still a result file in midas2_output/merge/snps/snps_summary.tsv
in following  ：
sample_name	species_id	genome_length	covered_bases	total_depth	aligned_reads	mapped_reads	fraction_covered	mean_coverage
LRDYA	145629	1285866	1167684	3404115544	27037703	22710376	0.908	2915.271
LRHYYA	145629	1285866	1162023	1681553770	13627927	11225812	0.904	1447.092
LRLSA	145629	1285866	1000914	2196377401	20331484	14671431	0.778	2194.372
LRQHWA	145629	1285866	1218182	4916836536	35987201	32797583	0.947	4036.208
LRQHYWA	145629	1285866	1190328	3122025362	23793590	20828196	0.926	2622.828

it seems that it merge results selectively,but i don't know the reason .

**Comment by luoqingqing777** [comment]
Hello!
I changed the genome_coverage limitation,and reruned with `midas2 merge_snps --samples_list list_of_samples.tsv --midasdb_name gtdb --midasdb_dir my_midasdb_Catellicoccus --genome_coverage 0.0 --num_cores 10 midas2_output/merge` 

this time,result file in `midas2_output/merge/snps/snps_summary.tsv` contains information of every sample,but still donot have Per-species SNPs Info Files  `145629.snps_freq.tsv.lz4`,`145629.snps_depth.tsv.lz4`and `145629.snps_info.tsv.lz4` in merge/snps/
with error:
1654781471.3:  Across samples population SNV calling in subcommand merge_snps with args
1654781471.3:  {
1654781471.3:      "subcommand": "merge_snps",
1654781471.3:      "force": false,
1654781471.3:      "debug": false,
1654781471.3:      "zzz_worker_mode": false,
1654781471.3:      "batch_branch": "master",
1654781471.3:      "batch_memory": 378880,
1654781471.3:      "batch_vcpus": 48,
1654781471.3:      "batch_queue": "pairani",
1654781471.3:      "batch_ecr_image": "pairani:latest",
1654781471.3:      "midas_outdir": "midas2_output/merge",
1654781471.3:      "samples_list": "list_of_samples.tsv",
1654781471.3:      "midasdb_name": "gtdb",
1654781471.3:      "midasdb_dir": "my_midasdb_Catellicoccus",
1654781471.3:      "species_list": null,
1654781471.3:      "genome_depth": 5.0,
1654781471.3:      "genome_coverage": 0.0,
1654781471.3:      "sample_counts": 2,
1654781471.3:      "site_depth": 5,
1654781471.3:      "site_ratio": 3.0,
1654781471.3:      "site_prev": 0.9,
1654781471.3:      "snv_type": "common",
1654781471.3:      "snp_pooled_method": "prevalence",
1654781471.3:      "snp_maf": 0.05,
1654781471.3:      "snp_type": "bi, tri, quad",
1654781471.3:      "locus_type": "any",
1654781471.3:      "num_cores": 10,
1654781471.3:      "chunk_size": 1000000,
1654781471.3:      "advanced": false,
1654781471.3:      "robust_chunk": false
1654781471.3:  }
1654781471.7:  1 species pass the filter
1654781471.7:  Create OUTPUT directory.
1654781471.7:  'rm -rf midas2_output/merge/snps'
1654781471.7:  'mkdir -p midas2_output/merge/snps'
1654781471.7:  Create TEMP directory.
1654781471.7:  'rm -rf midas2_output/merge/temp/snps'
1654781471.7:  'mkdir -p midas2_output/merge/temp/snps'
1654781471.7:  MIDAS2::write_species_summary::start
1654781471.7:  MIDAS2::write_species_summary::finish
1654781472.7:  MIDAS2::design_chunks::start
1654781472.8:  ================= Total number of compute chunks: 2
1654781472.8:  MIDAS2::design_chunks::finish
1654781472.8:  MIDAS2::multiprocessing_map::start
1654781472.8:    MIDAS2::process::145629-0::start snps_worker
1654781472.8:      MIDAS2::chunk_worker::145629-0::start accumulate_samples
1654781472.8:    MIDAS2::process::145629-1::start snps_worker
1654781472.8:      MIDAS2::chunk_worker::145629-1::start accumulate_samples
1654781472.8:    MIDAS2::process::145629--1::wait collect_chunks
1654781472.9:  WARNING: Non-zero exit code 141 from reader of midas2_output/ASQHA/snps/145629.snps.tsv.lz4.
1654781472.9:  WARNING: Non-zero exit code 141 from reader of midas2_output/ASQHA/snps/145629.snps.tsv.lz4.
1654781472.9:    MIDAS2::process::145629--1::start collect_chunks
cat: midas2_output/merge/temp/snps/145629/cid.0_snps_info.tsv.lz4: No such file or directory
cat: midas2_output/merge/temp/snps/145629/cid.1_snps_info.tsv.lz4: No such file or directory
1654781472.9:  Bugs in the codes, keep the outputs for debugging purpose.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 270, in process
    snps_worker(species_id, chunk_id)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 293, in snps_worker
    chunk_worker(chunks_of_sites[chunk_id][0])
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 345, in chunk_worker
    accumulate(accumulator, proc_args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 378, in accumulate
    for row in select_from_tsv(stream, schema=curr_schema, selected_columns=snps_pileup_basic_schema, result_structure=dict):
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 392, in select_from_tsv
    assert False, f"Line {i + j} has {len(values)} columns;  was expecting {len(headers)}."
AssertionError: Line 0 has 13 columns;  was expecting 8.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/home/user02/miniconda3/envs/midas2.0/bin/midas2", line 8, in <module>
    sys.exit(main())
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/__main__.py", line 24, in main
    return subcommand_main(subcommand_args)
  File "/media/home/user02/miniconda3/envs/midas2.0/bin/midas2", line 8, in <module>
    sys.exit(main())
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/__main__.py", line 24, in main
    return subcommand_main(subcommand_args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 664, in main
    merge_snps(args)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 653, in merge_snps
    raise error
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 643, in merge_snps
    proc_flags = multiprocessing_map(process, arguments_list, args.num_cores)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 532, in multiprocessing_map
    return _multi_map(func, items, num_procs, multiprocessing.Pool)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/site-packages/midas2/common/utils.py", line 520, in _multi_map
    return p.map(func, items, chunksize=1)
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/media/home/user02/miniconda3/envs/midas2.0/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value

Thank you so much

**Comment by zhaoc1** [comment]
Yes, only sufficiently abundant and prevalent species will be included for the population SNV analysis (`merge_snps`), and you can adjust the cutoff via command line. 

I would suggest the following three pages for the selection of species for population SNV compute (1) https://midas2-tutorial.readthedocs.io/en/stable/species.html (2) https://midas2-tutorial.readthedocs.io/en/stable/snv.html (3) https://midas2-tutorial.readthedocs.io/en/stable/advanced_topics.html

**Comment by luoqingqing777** [comment]
Thanks so much for your kind help.
MIDAS2 is really high-efficiency and  Work Easy ! 
While i was dealing with outcomes, some results represent "-1" `in snps_freq.tsv.lz4.` I can not understand what "-1"means ?it seems that minor allele frequency should between 0 to 0.5, but there are results that above 0.5 and also  -1 ;So it made me little confused.
Waiting for your kind reply,Thanks a lot

**Comment by zhaoc1** [comment]
Thanks. "-1" encodes for NA (missing values). The allele frequency of the population-wide minor allele can be [0, 1]. As for how the population SNPs are computed, please refer to https://midas2.readthedocs.io/en/latest/advanced_topics.html#population-snv-calling.

**Comment by luoqingqing777** [comment]
Thanks for your kind reply! After comparation of merge_results and simple sample results ,i seems the pipeline have alrealy taken ref_allele  as major_allele by default, the most common allele in the remaining three  alleles will be taken as minor_allele. That can explain why `minor_allele:`  **second most** common allele frequency can above 0.5.

There is another question i am not sure. In `merge/snps/XXX.snps_info.tsv.lz4` exists one colums as amino_acids. Is the order of them consistant with "1A 2C 3G 4T"? 
For example in one snp_site , amino_acid is `F,C,S,Y`. If it is consistant with order of "ACGT" ,it mean when this allele is A it will encode amino_acid F ,when  allele is G it will encode amino_acid S. 
I means is the oder of amino_acid  have relation with one fixed oder of nucleotide like ACGT,TAGC or something?

Thanks so much ,waiting for your kind help~

**Comment by zhaoc1** [comment]
> There is another question i am not sure. In merge/snps/XXX.snps_info.tsv.lz4 exists one colums as amino_acids. Is the order of them consistant with "1A 2C 3G 4T"?

I think this page can answer your question. https://midas2.readthedocs.io/en/latest/snv_module.html#across-samples
